# Generated by Django 4.2.6 on 2023-11-21 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('data_rozpoczecia', models.DateField()),
                ('termin_wykonania', models.DateField()),
                ('status', models.CharField(choices=[('W trakcie', 'W trakcie'), ('Zakończony', 'Zakończony')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zespol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('data_utworzenia', models.DateField(auto_now_add=True)),
                ('czlonkowie', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('data_rozpoczecia', models.DateField()),
                ('termin_wykonania', models.DateField()),
                ('priorytet', models.CharField(choices=[('Wysoki', 'Wysoki'), ('Średni', 'Średni'), ('Niski', 'Niski')], max_length=50)),
                ('status', models.CharField(choices=[('Nowe', 'Nowe'), ('W trakcie', 'W trakcie'), ('Zakońcozne', 'Zakończone')], max_length=50)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementsystem.projekt')),
                ('przypisany_uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zespoly', models.ManyToManyField(blank=True, to='managementsystem.zespol')),
            ],
        ),
    ]
