# Generated by Django 4.2.6 on 2023-11-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadanie',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zadania', to='managementsystem.projekt'),
        ),
    ]
